from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e58207aeee'
down_revision = '452dee38738f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_header', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('color_footer', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('color_text', sa.String(length=7), nullable=True))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('color_text')
        batch_op.drop_column('color_footer')
        batch_op.drop_column('color_header')